
module.exports = {
    "token": "MTE5NjIxMTk3MTg3NjQ2NjgzOA.GZi2-2.c51HLKJLAKŞmnglşFJNLADSGNŞLASDSŞGANSLŞMGASDLJANSLOŞQWIURTUYEOQWYTOPQUYWOUTYQWIOPUYOPTUQWO MALMISIN ORXSBU EVLADI",
    "prefix": "."
  };